# Polyglot
languages: ["en", "es", "de", "fr", "ru", "nl", "he", "ko", "zh-CN", "pt-BR", "ar", "jp", "it", "tr"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public", "sitemap", "CNAME"]
parallel_localization: false
url: https://polyglot.untra.io

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# author
author:
  name: 'Samuel Volin'
  url: https://github.com/untra

# google analytics
ga_tag: G-HWC3D32MT8


plugins: [jekyll-polyglot, jekyll-paginate, jekyll-redirect-from]
# Permalinks
permalink: pretty

include: ['_pages']
exclude: ['LICENSE.md', 'README.md', 'publi.sh', 'Gemfile.lock', 'Gemfile']
# Setup
title: Polyglot
tagline: 'Straightforward I18n for Jekyll Blogs'

# data
sidebar:
  hello:
    en: Hello!
    es: ¡hola!
    fr: Bonjour!
    de: Hallo!
    ru: Привет!
    nl: Hallo!
    he: "שלום!"
    ko: 안녕하세요!
    zh-CN: 你好！
    pt-BR: Olá!
    ar: مرحبا!
    jp: こんにちは！
    it: Ciao!
    tr: Merhaba!
  viewsource:
    en: view this page source on github
    es: ver el código fuente de esta página en github
    fr: voir le code source de cette page sur github
    de: seite quellcode auf github ansehen
    ru: посмотреть исходный код этой страницы на github
    nl: codebron bekijken op github
    he: צפייה בקוד מקור של דף זה בגיטהאב
    ko: 이 페이지의 소스 코드를 깃허브에서 보기
    zh-CN: 查看此页面的源代码在 github
    pt-BR: ver o código fonte desta página no github
    ar: عرض كود المصدر لهذه الصفحة على github
    jp: このページのソースコードをgithubで見る
    it: visualizza il codice sorgente di questa pagina su github
    tr: bu sayfanın kaynak kodunu github'da görüntüle
  description:
    zh-CN: 一款为 <a href="http://jekyllrb.com" target="_blank">Jekyll</a> 提供 i18n 多语言功能的插件，方便快捷，适用于各类大小博客。<a href="https://github.com/untra" target="_blank">@untra</a> 出品。
    ko: <a href="https://github.com/untra" target="_blank">@untra</a>가 만든, 크고 작은 블로그 모두가 빠르고 직관적인 다국어 지원을 가능케 하는 i18n 지원 <a href="http://jekyllrb.com" target="_blank">Jekyll</a> 플러그인.
    he: תוסף תמיכה ב-i18n עבור <a href="http://jekyllrb.com" target="_blank">Jekyll</a> שהופך את התמיכה מרובת שפות למהירה ואינטואיטיבית, עבור בלוגים גדולים וקטנים. תוצרת <a href="https://github.com/untra" target="_blank">@untra</a>.
    nl: Een plug-in voor internationlisering van <a href="http://jekyllrb.com" target="_blank">Jekyll</a> die meertalige ondersteuning snel en intuïtief maakt, voor blogs groot en klein. Gemaakt door <a href="https://github.com/untra" target="_blank">@untra</a>.
    ru: Плагин поддержки i18n для <a href="http://jekyllrb.com" target="_blank">Jekyll</a> что делает поддержку нескольких языков быстрой и интуитивно понятной, для больших и маленьких блогов. Сделано в <a href="https://github.com/untra" target="_blank">@untra</a>.
    de: Ein sprachunterstützung plugin für <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, die Unterstützung der Internationalisierung schnell und intuitiv macht, für Blogs groß und klein. Hergestellt von <a href="https://github.com/untra" target="_blank">@untra</a>.
    es: Un plugin soporte de i18n para <a href="http://jekyllrb.com" target="_blank">Jekyll</a> que hace soporte de internacionalización rápida e intuitiva, para los blogs grandes y pequeños. Hecho por <a href="https://github.com/untra" target="_blank">@untra</a>.
    fr: Un plugin de support de i18n pour <a href="http://jekyllrb.com" target="_blank">Jekyll</a> qui fait support de l'internationalisation rapide et intuitive, pour tous les blogs. Réalisé par <a href="https://github.com/untra" target="_blank">@untra</a>.
    en: A i18n support plugin for <a href="http://jekyllrb.com" target="_blank">Jekyll</a> that makes multi-language support fast and intuitive, for blogs big and small. Made by <a href="https://github.com/untra" target="_blank">@untra</a>.
    pt-BR: Um plugin de suporte i18n para <a href="http://jekyllrb.com" target="_blank">Jekyll</a> que torna o suporte a vários idiomas rápido e intuitivo, para blogs grandes e pequenos. Feito por <a href="https://github.com/untra" target="_blank">@untra</a>.
    ar: إضافة دعم i18n لـ <a href="http://jekyllrb.com" target="_blank">Jekyll</a> تجعل دعم اللغات المتعددة سريعاً وبديهياً، للمدونات الكبيرة والصغيرة. من صنع <a href="https://github.com/untra" target="_blank">@untra</a>.
    jp: <a href="http://jekyllrb.com" target="_blank">Jekyll</a>用のi18nサポートプラグインで、大小を問わずブログの多言語サポートを高速で直感的にします。<a href="https://github.com/untra" target="_blank">@untra</a>が作成。
    it: Un plugin di supporto i18n per <a href="http://jekyllrb.com" target="_blank">Jekyll</a> che rende il supporto multilingue veloce e intuitivo, per blog grandi e piccoli. Realizzato da <a href="https://github.com/untra" target="_blank">@untra</a>.
    tr: Büyük ve küçük bloglar için çoklu dil desteğini hızlı ve sezgisel hale getiren <a href="http://jekyllrb.com" target="_blank">Jekyll</a> için bir i18n destek eklentisi. <a href="https://github.com/untra" target="_blank">@untra</a> tarafından yapıldı.

keywords: 
  en: multilingual, i18n, jekyll, polyglot, fast, intuitive, untra, github, pages, blog, plugin, ruby, gem, internationalization, localization, translation, language, support, multi-language, multi-lingual
  ko: 다국어, i18n, 제킬, 다국어, 빠른, 직관적인, untra, 깃허브, 페이지, 블로그, 플러그인, 루비, 젬, 국제화, 현지화, 번역, 언어, 지원, 다국어, 다국어
  he: רב-לשוני, i18n, ג'קיל, רב-לשוני, מהיר, אינטואיטיבי, untra, גיטהאב, דפים, בלוג, תוסף, רובי, ג'ם, בינלאומיות, לוקליזציה, תרגום, שפה, תמיכה, רב-לשוני, רב-לשוני
  nl: meertalig, i18n, jekyll, meertalig, snel, intuïtief, untra, github, pagina's, blog, plugin, ruby, gem, internationalisering, lokalisatie, vertaling, taal, ondersteuning, meertalig, meertalig
  ru: многоязычный, i18n, джекилл, полиглот, быстрый, интуитивный, untra, гитхаб, страницы, блог, плагин, рубин, гем, интернационализация, локализация, перевод, язык, поддержка, многоязычный, многоязычный
  de: mehrsprachig, i18n, jekyll, polyglot, schnell, intuitiv, untra, github, seiten, blog, plugin, ruby, gem, internationalisierung, lokalisierung, übersetzung, sprache, unterstützung, mehrsprachig, mehrsprachig
  es: multilingüe, i18n, jekyll, políglota, rápido, intuitivo, untra, github, páginas, blog, plugin, ruby, gem, internacionalización, localización, traducción, idioma, soporte, multilingüe, multilingüe
  fr: multilingue, i18n, jekyll, polyglotte, rapide, intuitif, untra, github, pages, blog, plugin, ruby, gem, internationalisation, localisation, traduction, langue, support, multilingue, multilingue
  pt-BR: multilíngue, i18n, jekyll, políglota, rápido, intuitivo, untra, github, páginas, blog, plugin, ruby, gem, internacionalização, localização, tradução, idioma, suporte, multilíngue, multilíngue
  zh-CN: 多语言, i18n, 杰基尔, 多语种, 快速, 直观, untra, 깃허브, 页面, 博客, 插件, 卢比, gem, 国际化, 本地化, 翻译, 语言, 支持, 多语言, 多语言
  ar: متعدد اللغات, i18n, جيكيل, متعدد اللغات, سريع, بديهي, untra, جيثب, صفحات, مدونة, إضافة, روبي, gem, تدويل, توطين, ترجمة, لغة, دعم, متعدد اللغات, متعدد اللغات
  jp: 多言語, i18n, ジェキル, 多言語, 高速, 直感的, untra, ギットハブ, ページ, ブログ, プラグイン, ルビー, gem, 国際化, ローカライゼーション, 翻訳, 言語, サポート, 多言語, 多言語
  it: multilingue, i18n, jekyll, polyglot, veloce, intuitivo, untra, github, pagine, blog, plugin, ruby, gem, internazionalizzazione, localizzazione, traduzione, lingua, supporto, multilingue
  tr: çok dilli, i18n, jekyll, polyglot, hızlı, sezgisel, untra, github, sayfalar, blog, eklenti, ruby, gem, uluslararasılaştırma, yerelleştirme, çeviri, dil, destek, çok dilli
description:
  zh-CN: 一款为 Jekyll 提供 i18n 多语言功能的插件，方便快捷，适用于各类大小博客
  ko: 크고 작은 블로그 모두가 빠르고 직관적인 다국어 지원을 가능케 하는 i18n 지원 Jekyll 플러그인.
  he: תוסף תמיכה ב-i18n עבור Jekyll שהופך את התמיכה מרובת שפות למהירה ואינטואיטיבית, עבור בלוגים גדולים וקטנים. תוצרת.
  nl: Een plug-in voor internationlisering van Jekyll die meertalige ondersteuning snel en intuïtief maakt, voor blogs groot en klein.
  ru: Плагин поддержки i18n для Jekyll что делает поддержку нескольких языков быстрой и интуитивно понятной, для больших и маленьких блогов.
  de: Ein sprachunterstützung plugin für Jekyll, die Unterstützung der Internationalisierung schnell und intuitiv macht, für Blogs groß und klein.
  es: Un plugin soporte de i18n para Jekyll que hace soporte de internacionalización rápida e intuitiva, para los blogs grandes y pequeños.
  fr: Un plugin de support de i18n pour Jekyll qui fait support de l'internationalisation rapide et intuitive, pour tous les blogs.
  en: A i18n support plugin for Jekyll that makes multi-language support fast and intuitive, for blogs big and small.
  pt-BR: Um plugin de suporte i18n para Jekyll que torna o suporte a vários idiomas rápido e intuitivo, para blogs grandes e pequenos.
  ar: إضافة دعم i18n لـ Jekyll تجعل دعم اللغات المتعددة سريعاً وبديهياً، للمدونات الكبيرة والصغيرة.
  jp: Jekyll用のi18nサポートプラグインで、大小を問わずブログの多言語サポートを高速で直感的にします。
  it: Un plugin di supporto i18n per Jekyll che rende il supporto multilingue veloce e intuitivo, per blog grandi e piccoli.
  tr: Büyük ve küçük bloglar için çoklu dil desteğini hızlı ve sezgisel hale getiren Jekyll için bir i18n destek eklentisi.

paginate: 5
# Custom vars
version: 1.12.0
# practical values langsep are "|", "•", "·", "-", "–"
langsep: "•"

github:
  repo: https://github.com/untra/polyglot

whitelist:
  - jekyll-redirect-from